# Generated by Django 4.0.6 on 2022-07-05 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodev', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='activity',
            field=models.CharField(choices=[('meditation', 'Maditation')], max_length=255),
        ),
    ]
