# Generated by Django 4.0.6 on 2022-07-05 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodev', '0002_alter_project_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='activity',
            field=models.CharField(choices=[('meditation', 'Maditation'), ('stretch', 'Stretch'), ('run', 'Run'), ('take a walk', 'Take a walk'), ('listen to music', 'Listen to music'), ('take a glass of water', 'Take a glass of water')], max_length=255),
        ),
    ]
