# Generated by Django 4.0.5 on 2022-07-11 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodev', '0004_remove_project_activity_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profession',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
