# Generated by Django 4.0.5 on 2022-07-12 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodev', '0005_alter_user_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
