# Generated by Django 4.0.5 on 2022-07-12 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prodev', '0006_alter_project_date_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time_Worked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_worked', models.IntegerField(default=0)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prodev.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prodev.user')),
            ],
        ),
    ]
